export default [{ id: 1, name: 'John' },
                { id: 2, name: 'Kerry' },
                { id: 3, name: 'Elize' },
                { id: 4, name: 'Anita' },
                { id: 5, name: 'Joe' },
                { id: 6, name: 'Simpson' },
                { id: 7, name: 'Queer' },
                { id: 8, name: 'Abidale' },
                { id: 9, name: 'Momy' },
                { id: 10, name: 'Sanders' },
                { id: 11, name: 'Donald' },
                { id: 12, name: 'Brown' }];
